setting:
  service_name: notification
  version: 0.0.1

service:
  name: notification
  http_port: ':8080'

mysql:
  db_host: localhost
  db_port: 3306
  db_name: notification
  db_user: root
  db_password: ''
  db_driver: mysql

kafka:
  host: localhost
  port: 9092
  group_id: kafka-notification-v1
  topic: notification
  version: 1.0.0
